### ISSUE TITLE
Push 0.1.12 to Clojars?

### ISSUE THREAD

**Issue by venantius** [zcaudate/iroh#2]
Hey - 

I just noticed that you've bumped the version to 0.1.12 - any chance of seeing a release pushed up to Clojars? Thanks!

 - V

**Comment by zcaudate** [comment]
Stay tuned.... 

I'm planning to deprecate this library... The main bulk of iroh is in hara.reflect and I'm planning to integrate the iroh.core macros into vinyasa directly.

 I'm not actually sure what I added to 0.1.12... So just keep using 0.1.11 :)

**Comment by venantius** [comment]
Oh, radical. I was going to inject some of this into a plugin I'm working on, so definitely keep me posted.

**Comment by hoebat** [comment]
Okay. Its done. Please see https://github.com/zcaudate/vinyasa for updated docs

**Comment by venantius** [comment]
woo!

On Fri, Jan 16, 2015 at 2:44 PM, Chris Zheng notifications@github.com
wrote:

> Okay. Its done. Please see https://github.com/zcaudate/vinyasa for
> updated docs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zcaudate/iroh/issues/2#issuecomment-70334953.

## 

# 

venanti.us

# 203.918.2328
